fix lambda zip errors when docker creates files as root
aws_lambda hook can generate an error like:

```
[runway] method runway.cfngin.hooks.aws_lambda.upload_lambda_functions threw an exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'REQUESTED'
During handling of the above exception, another exception occurred:
...
PermissionError: [Errno 1] Operation not permitted: '/home/user/.runway_cache/cfnginy7x0_mye/tabulate-0.8.9.dist-info'
```

Runway shouldn't bomb out due to errors in cleaning up the temporary
directory. This approach moves the cleanup to an explicit method that
handles the edge case.