add parallel module execution (#83)
Would have been nice to have kept py2 compatibility, but it (by way of the `futures` pypi package)
causes errors like:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```